name: 'Create Pull Request'
description: 'Create a pull request using GitHub API'
inputs:
  token:
    description: 'GitHub token'
    required: true
  title:
    description: 'PR title'
    required: true
  branch:
    description: 'Branch name'
    required: true
  base:
    description: 'Base branch'
    required: true
    default: 'main'
  body:
    description: 'PR body'
    required: false
outputs:
  pull-request-url:
    description: 'URL of the created pull request'
    value: ${{ steps.create-pr.outputs.url }}
runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      id: create-pr
      shell: bash
      run: |
        response=$(curl -s -X POST \
          -H "Authorization: token ${{ inputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
            "title": "${{ inputs.title }}",
            "head": "${{ inputs.branch }}",
            "base": "${{ inputs.base }}",
            "body": "${{ inputs.body }}"
          }')
        
        # エラーチェックを追加
        url=$(echo "$response" | jq -r '.html_url // empty')
        if [ -n "$url" ] && [ "$url" != "null" ]; then
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "Pull Request created: $url"
        else
          echo "Error creating PR:"
          echo "$response"
          exit 1
        fi