name: 'Notify Discord'
description: 'Send notification to Discord webhook'
inputs:
  webhook-url:
    description: 'Discord webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Discord notification
      shell: bash
      run: |
        # jqを使って安全にJSONを作成
        json_data=$(jq -n \
          --arg content "${{ inputs.message }}" \
          '{
            content: $content
          }')
        
        echo "Sending Discord notification..."
        
        response=$(curl -s -H "Content-Type: application/json" \
          -d "$json_data" \
          "${{ inputs.webhook-url }}")
        
        echo "Discord response: $response"