name: 'Notify Discord'
description: 'Send notification to Discord webhook'
inputs:
  webhook-url:
    description: 'Discord webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Discord notification
      shell: bash
      run: |
        curl -H "Content-Type: application/json" \
          -d '{
            "content": "${{ inputs.message }}"
          }' \
          "${{ inputs.webhook-url }}"