name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 必要なパッケージをインストールして、pnpm run buildを実行する
      - uses: withastro/action@v2
