name: Preview

on:
  pull_request:

jobs:
  build_and_deploy_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout preview repo
        uses: actions/checkout@v4
        with:
          repository: GoWorkshopConference/2025-preview
          path: preview
          ssh-key: ${{ secrets.PREVIEW_DEPLOY_KEY }}
      - name: Build 
        uses: withastro/action@v3
        with:
          path: main
        env:
          VITE_APP_BASE_URL: /2025-preview/${{ github.event.number }}
      - name: Deploy to preview repo
        run: |
          rm -rf ./preview/$PR_NUMBER
          cp -r ./main/dist ./preview/$PR_NUMBER
          cd ./preview
          
          # Set bot user identity
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if [ -z "$(git status --porcelain)" ]; then 
            echo "::notice ::No changes detected, exiting"
            exit 0
          fi

          git add .
          git commit -m "Update preview"
          git push
        env:
          PR_NUMBER: ${{ github.event.number }}
